# -*- coding: utf-8 -*-
"""OnlineDictionary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12FQjPAQ0blTqfBJDLfC-_cXCWDu4Fwy0
"""

import requests
from bs4 import BeautifulSoup

#!pip install requests
#!pip install html5lib

a=input("Enter the word u want to know the meaning of:")

url="https://www.dictionary.com/browse/"+a
#print(url)

r=requests.get(url)
htmlContent=r.content
#print(htmlContent)

soup=BeautifulSoup(htmlContent,'html.parser')
#print(soup.prettify)

soup.find_all(class_='one-click-content css-1p89gle e1q3nk1v4', limit=4)

for meaning in soup.findAll(class_='one-click-content css-1p89gle e1q3nk1v4', limit=4):
  
  #print(parargraph.string)
  print(str(meaning.text)+",")
